import type { SpeciesRegulation } from '@/types'

export const FISHING_CATEGORIES = [
  { id: 'coastal', label: 'Mer côtière', icon: '🏖️', description: 'Pêche depuis la côte ou en bord de mer' },
  { id: 'boat', label: 'En bateau', icon: '⛵', description: 'Pêche depuis un bateau en mer' },
  { id: 'freshwater_lake', label: 'Lac', icon: '🏞️', description: 'Pêche en lac ou étang' },
  { id: 'freshwater_river', label: 'Rivière', icon: '🏞️', description: 'Pêche en rivière ou cours d\'eau' },
  { id: 'reservoir', label: 'Réservoir', icon: '💧', description: 'Pêche en réservoir ou plan d\'eau artificiel' },
] as const

export const SPECIES_REGULATIONS: Record<string, SpeciesRegulation> = {
  bar_commun: {
    id: 'bar_commun',
    name: 'Bar commun (Loup)',
    scientificName: 'Dicentrarchus labrax',
    minSize: { atlantic: 42, mediterranean: 25, default: 42 },
    quotaPerDay: { recreational: 3 },
    closedSeasons: [{ region: 'atlantic', start: '01-01', end: '01-31' }],
    category: ['coastal', 'boat'],
    icon: '🐟',
  },
  dorade_royale: {
    id: 'dorade_royale',
    name: 'Daurade royale',
    scientificName: 'Sparus aurata',
    minSize: { atlantic: 25, mediterranean: 20, default: 25 },
    quotaPerDay: { recreational: null },
    category: ['coastal', 'boat'],
    icon: '🐠',
  },
  maquereau: {
    id: 'maquereau',
    name: 'Maquereau',
    scientificName: 'Scomber scombrus',
    minSize: { default: 20 },
    quotaPerDay: { recreational: null },
    category: ['coastal', 'boat'],
    icon: '🐟',
  },
  truite_fario: {
    id: 'truite_fario',
    name: 'Truite fario',
    scientificName: 'Salmo trutta',
    minSize: { default: 23 },
    quotaPerDay: { recreational: 6 },
    closedSeasons: [{ region: 'general', start: '09-20', end: '03-14' }],
    category: ['freshwater_river'],
    icon: '🐟',
  },
  truite_arc_en_ciel: {
    id: 'truite_arc_en_ciel',
    name: 'Truite arc-en-ciel',
    scientificName: 'Oncorhynchus mykiss',
    minSize: { default: 23 },
    quotaPerDay: { recreational: 6 },
    category: ['freshwater_river', 'freshwater_lake', 'reservoir'],
    icon: '🐟',
  },
  brochet: {
    id: 'brochet',
    name: 'Brochet',
    scientificName: 'Esox lucius',
    minSize: { default: 60 },
    quotaPerDay: { recreational: 2 },
    closedSeasons: [{ region: 'general', start: '01-25', end: '04-30' }],
    category: ['freshwater_lake', 'freshwater_river', 'reservoir'],
    icon: '🐟',
  },
  sandre: {
    id: 'sandre',
    name: 'Sandre',
    scientificName: 'Sander lucioperca',
    minSize: { default: 40 },
    quotaPerDay: { recreational: null },
    category: ['freshwater_lake', 'freshwater_river', 'reservoir'],
    icon: '🐟',
  },
  perche: {
    id: 'perche',
    name: 'Perche',
    scientificName: 'Perca fluviatilis',
    minSize: { default: 15 },
    quotaPerDay: { recreational: null },
    category: ['freshwater_lake', 'freshwater_river', 'reservoir'],
    icon: '🐟',
  },
  carpe_commune: {
    id: 'carpe_commune',
    name: 'Carpe commune',
    scientificName: 'Cyprinus carpio',
    minSize: { default: 40 },
    quotaPerDay: { recreational: null },
    notes: 'Pratique du no-kill très répandue',
    category: ['freshwater_lake', 'freshwater_river', 'reservoir'],
    icon: '🐟',
  },
  anguille: {
    id: 'anguille',
    name: 'Anguille',
    scientificName: 'Anguilla anguilla',
    minSize: { default: 40 },
    quotaPerDay: { recreational: 3 },
    notes: 'Espèce en danger critique - réglementation stricte',
    category: ['freshwater_river', 'freshwater_lake', 'coastal'],
    icon: '🐍',
  },
  turbot: {
    id: 'turbot',
    name: 'Turbot',
    scientificName: 'Scophthalmus maximus',
    minSize: { default: 30 },
    quotaPerDay: { recreational: null },
    category: ['coastal', 'boat'],
    icon: '🐟',
  },
  sole: {
    id: 'sole',
    name: 'Sole',
    scientificName: 'Solea solea',
    minSize: { default: 24 },
    quotaPerDay: { recreational: null },
    category: ['coastal', 'boat'],
    icon: '🐟',
  },
  merlan: {
    id: 'merlan',
    name: 'Merlan',
    scientificName: 'Merlangius merlangus',
    minSize: { default: 23 },
    quotaPerDay: { recreational: null },
    category: ['coastal', 'boat'],
    icon: '🐟',
  },
  lieu_jaune: {
    id: 'lieu_jaune',
    name: 'Lieu jaune (Doré)',
    scientificName: 'Pollachius pollachius',
    minSize: { default: 30 },
    quotaPerDay: { recreational: null },
    category: ['coastal', 'boat'],
    icon: '🐟',
  },
}

export const FISHING_TECHNIQUES = [
  { id: 'surfcasting', label: 'Surfcasting', icon: '🏖️', categories: ['coastal'] },
  { id: 'spinning', label: 'Lancer-ramener', icon: '🎣', categories: ['coastal', 'boat', 'freshwater_lake', 'freshwater_river', 'reservoir'] },
  { id: 'fly', label: 'Mouche', icon: '🪰', categories: ['freshwater_river', 'freshwater_lake'] },
  { id: 'bottom', label: 'Fond', icon: '⚓', categories: ['coastal', 'boat', 'freshwater_lake', 'freshwater_river'] },
  { id: 'trolling', label: 'Traîne', icon: '⛵', categories: ['boat', 'freshwater_lake'] },
  { id: 'jigging', label: 'Jigging', icon: '🎣', categories: ['boat'] },
  { id: 'bait', label: 'Vif / Appât', icon: '🪱', categories: ['coastal', 'boat', 'freshwater_lake', 'freshwater_river', 'reservoir'] },
  { id: 'feeder', label: 'Feeder', icon: '🎣', categories: ['freshwater_lake', 'freshwater_river', 'reservoir'] },
  { id: 'match', label: 'Match', icon: '🎣', categories: ['freshwater_lake', 'freshwater_river'] },
  { id: 'carpfishing', label: 'Carpfishing', icon: '🐟', categories: ['freshwater_lake', 'reservoir'] },
] as const
